server:
  port: 8081
  servlet:
    context-path: /orderservice

spring:
  datasource:
    url: jdbc:mysql://124.223.60.96:3306/proxy?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: apiuser
    password: apiuser
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: edu.nyit.orderservice.entity
  mapper-locations: classpath:mapper/*Mapper.xml


